[package]
name = "aztec-sandbox" # Aztec Version Manager
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
reqwest = { version = "0.11.16", default-features = false, features = [
    "rustls-tls",
    "blocking",
] }
tar = "0.4"
flate2 = "1.0"