name: Publish Aztec-Sandbox

on:
  workflow_dispatch:
  # schedule:
  #   # Run a nightly release at 2 AM UTC
  #   - cron: "0 2 * * *"

permissions:
  # Necessary to upload new release artifacts
  contents: write

jobs:
  build-apple-darwin:
    runs-on: macos-latest
    env:
      CROSS_CONFIG: ${{ github.workspace }}/.github/Cross.toml
      CACHED_PATHS: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Setup for Apple Silicon
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer/
          echo "SDKROOT=$(xcrun -sdk macosx$(sw_vers -productVersion) --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx$(sw_vers -productVersion) --show-sdk-platform-version)" >> $GITHUB_ENV

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ env.CACHED_PATHS }}
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build environment and Compile
        run: |
          cargo build --release --target ${{ matrix.target }}

      - uses: actions/cache/save@v3
        # Don't create cache entries for the merge queue.
        if: ${{ steps.cache.outputs.cache-hit != 'true' && github.event_name != 'merge_group' }}
        with:
          path: ${{ env.CACHED_PATHS }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      
      - name: Package artifacts
        run: |
          mkdir dist
          cp ./target/${{ matrix.target }}/release/aztec-sandbox ./dist/nargo
          7z a -ttar -so -an ./dist/* | 7z a -si ./aztec-sandbox-${{ matrix.target }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aztec-sandbox-${{ matrix.target }}
          path: ./dist/*
          retention-days: 3

      - name: Test built artifact
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          cp ./target/${{ matrix.target }}/release/aztec-sandbox ~/.cargo/bin/

          cd release-tests
          yarn install
          yarn test

      - name: Upload binaries to release tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: AztecProtocol/sandbox-version-manager
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./aztec-sandbox-${{ matrix.target }}.tar.gz
          asset_name: aztec-sandbox-${{ matrix.target }}.tar.gz
          overwrite: true
          tag: ${{ 'nightly' }} 

  build-linux:
    runs-on: ubuntu-22.04
    env:
      CROSS_CONFIG: ${{ github.workspace }}/.github/Cross.toml
      CACHED_PATHS: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ env.CACHED_PATHS }}
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build aztec-sandbox
        run: |
          cargo install cross --version 0.2.5 --force 
          cross build --release --target=${{ matrix.target }}

      - uses: actions/cache/save@v3
        # Don't create cache entries for the merge queue.
        if: ${{ steps.cache.outputs.cache-hit != 'true' && github.event_name != 'merge_group' }}
        with:
          path: ${{ env.CACHED_PATHS }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Package artifacts
        run: |
          mkdir dist
          cp ./target/${{ matrix.target }}/release/aztec-sandbox ./dist/nargo
          7z a -ttar -so -an ./dist/* | 7z a -si ./aztec-sandbox-${{ matrix.target }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aztec-sandbox-${{ matrix.target }}
          path: ./dist/*
          retention-days: 3

      - name: Test built artifact
        if: startsWith(matrix.target, 'x86_64-unknown-linux')
        run: |
          cp ./target/${{ matrix.target }}/release/aztec-sandbox ~/.cargo/bin/

          cd release-tests
          yarn install
          yarn test

      - name: Upload binaries to release tag
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'schedule' }}
        with:
          repo_name: AztecProtocol/sandbox-version-manager
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./aztec-sandbox-${{ matrix.target }}.tar.gz
          asset_name: aztec-sandbox-${{ matrix.target }}.tar.gz
      